### ISSUE TITLE
Error in production: bad timezone

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#161]
```
Jun 08 23:37:39 monica laravel: production.ERROR: InvalidArgumentException: Unknown or bad timezone (America/Argentina/ Buenos_Aires) in /home/forge/default/vendor/nesbot/carbon/src/Carbon/Carbon.php:252 Stack trace: 
#0 /home/forge/default/vendor/nesbot/carbon/src/Carbon/Carbon.php(571): Carbon\Carbon::safeCreateDateTimeZone('America/Argenti...') 
#1 /home/forge/default/app/Helpers/DateHelper.php(20): Carbon\Carbon::createFromFormat('Y-m-d H:i:s', Object(Carbon\Carbon), 'America/Argenti...') 
#2 /home/forge/default/app/Http/Controllers/DashboardController.php(92): App\Helpers\DateHelper::createDateFromFormat(Object(Carbon\Carbon), 'America/Argenti...') 
#3 [internal function]: App\Http\Controllers\DashboardController->index() 
#4 /home/forge/default/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array) 
#5 
```

**Comment by BerkhanBerkdemir** [comment]
config>app.php

'timezone' => 'UTC',
TO
'timezone' => 'America/Argentina/Buenos_Aires',

link : https://packagist.org/packages/gazugafan/laravel-timezone?q=

**Comment by djaiss** [comment]
This is now fixed.
