### ISSUE TITLE
Adding contact to existing activity is broken since 2.12

### ISSUE THREAD

**Issue by croesch** [monicahq/monica#2450]
If I try to add a person to an existing activity, (IMO) since the update to 2.12 it doesn't work. Creating activities with multiple contacts works but adding a contact not, the following error is shown:

```
Whoops! Something went wrong.

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`monica`.`activity_contact`, CONSTRAINT `activity_contact_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE) (SQL: insert into `activity_contact` (`activity_id`, `contact_id`) values (9, 3))

Back to homepage
```
Log file says:
```
[2019-02-17 00:47:15] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`monica`.`activity_contact`, CONSTRAINT `activity_c
ontact_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE) (SQL: insert into `activity_contact` (`activity_id`, `contact_id`) values (9, 3)) {"userId":1,"email":"XXX","exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mon
ica`.`activity_contact`, CONSTRAINT `activity_contact_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE) (SQL: insert into `activity_contact` (`activity_id`, `contact_
id`) values (9, 3)) at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 145
2 Cannot add or update a child row: a foreign key constraint fails (`monica`.`activity_contact`, CONSTRAINT `activity_contact_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE
 CASCADE) at /var/www/monica/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row:
 a foreign key constraint fails (`monica`.`activity_contact`, CONSTRAINT `activity_contact_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE) at /var/www/monica/vendor
/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `ac...', Array, Object(Closure))
#1 /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `ac...', Array, Object(Closure))
#2 /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `ac...', Array)
#3 /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2611): Illuminate\\Database\\Connection->insert('insert into `ac...', Array)
#4 /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(216): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php(850): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->attach(Object(App\\Models\\Account\\Activi
ty), Array, true)
#6 /var/www/monica/app/Http/Controllers/ActivitiesController.php(156): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->save(Object(App\\Models\\Account\\Activity))
#7 [internal function]: App\\Http\\Controllers\\ActivitiesController->update(Object(App\\Http\\Requests\\People\\ActivitiesRequest), Object(App\\Models\\Account\\Activity), Object(App\\Models\\Contact\\Contact))
#8 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update', Array)
#10 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Activiti
esController), 'update')
#11 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#12 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#13 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/monica/vendor/pragmarx/google2fa-laravel/src/Middleware.php(15): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): PragmaRX\\Google2FALaravel\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/monica/vendor/lahaxearnaud/laravel-u2f/src/http/Middleware/U2f.php(48): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Lahaxearnaud\\U2f\\Http\\Middleware\\U2f->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/monica/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/monica/app/Http/Middleware/EnsureEmailIsVerified.php(20): Illuminate\\Auth\\Middleware\\EnsureEmailIsVerified->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\EnsureEmailIsVerified->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/monica/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/monica/app/Http/Middleware/CheckCompliance.php(34): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\CheckCompliance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/monica/app/Http/Middleware/CheckVersion.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\CheckVersion->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/monica/app/Http/Middleware/CheckLocale.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\CheckLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/monica/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
...
```

Do you need any further information? Currently I try to work around by creating activities with all contacts in first place or delete an activity and recreate it with additional contacts.

**Comment by asbiin** [comment]
This is already fixed with #2418, we will release a fix version soon.

**Comment by croesch** [comment]
Thanks for the quick reply! Great then I'm looking forward updating to the fixed version.. but I'm wondering how the default prevention of the JS event could solve the SQL state problem.

I can work around the jumping to the dashboard by holding down `ctrl` while clicking, this way I create masses of tabs, but the contacts are added but still (using the click-workaround) I can't add contacts to existing activities resulting in the SQL error message.

**Comment by croesch** [comment]
Thanks for fixing it
