### ISSUE TITLE
Composer install: Safe\unlink undefined

### ISSUE THREAD

**Issue by daniele-athome** [monicahq/monica#2719]
I don't know if I'm missing something, but I was upgrading to 2.14.0 from an older version (around 2.11) and I got this error on running composer:

```
web@server:~/monica$ composer install --no-interaction --no-suggest --no-dev
> App\Helpers\ComposerScripts::preInstall
PHP Fatal error:  Uncaught Error: Call to undefined function Safe\unlink() in /home/web/monica/app/Helpers/ComposerScripts.php:49
Stack trace:
#0 /home/web/monica/app/Helpers/ComposerScripts.php(24): App\Helpers\ComposerScripts::clear()
#1 phar:///home/web/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(297): App\Helpers\ComposerScripts::preInstall(Object(Composer\Script\Event))
#2 phar:///home/web/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(219): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('App\\Helpers\\Com...', 'preInstall', Object(Composer\Script\Event))
#3 phar:///home/web/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///home/web/composer.phar/src/Composer/Installer.php(205): Composer\EventDispatcher\EventDispatcher->dispatchScript('pre-install-cmd', false)
#5 phar:///home/web/composer.phar/src/Composer/Command/InstallCommand.php(122): Composer\Installer->r in /home/web/monica/app/Helpers/ComposerScripts.php on line 49

Fatal error: Uncaught Error: Call to undefined function Safe\unlink() in /home/web/monica/app/Helpers/ComposerScripts.php:49
Stack trace:
#0 /home/web/monica/app/Helpers/ComposerScripts.php(24): App\Helpers\ComposerScripts::clear()
#1 phar:///home/web/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(297): App\Helpers\ComposerScripts::preInstall(Object(Composer\Script\Event))
#2 phar:///home/web/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(219): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('App\\Helpers\\Com...', 'preInstall', Object(Composer\Script\Event))
#3 phar:///home/web/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///home/web/composer.phar/src/Composer/Installer.php(205): Composer\EventDispatcher\EventDispatcher->dispatchScript('pre-install-cmd', false)
#5 phar:///home/web/composer.phar/src/Composer/Command/InstallCommand.php(122): Composer\Installer->r in /home/web/monica/app/Helpers/ComposerScripts.php on line 49
```

I noticed that you require `thecodingmachine/safe` in your composer.json, but your custom composer install script requires it, thus the loophole above.
I could probably fix this by adding the `--no-scripts` flag, but that's a workaround.

**Comment by asbiin** [comment]
That's really bad.
You can solve this by deleting the `vendor` directory, and rerun `composer install`

**Comment by daniele-athome** [comment]
>  You can solve this by deleting the vendor directory, and rerun composer install

I'm afraid that's not enough. I tested that, and I discovered that the call to `Safe::unlink` is caused by the presence of the file `bootstrap/cache/config.php`. It's ok but you should mention this in your upgrade docs.

**Comment by asbiin** [comment]
@daniele-athome you're right! Thanks
