### ISSUE TITLE
Erroneous data format for unserializing 'Symfony\Component\Routing\CompiledRoute'

### ISSUE THREAD

**Issue by nzubair** [monicahq/monica#3937]
**Describe the bug**
After following the instructions to install on Ubuntu, I'm receiving the following error when trying to navigate to the site:

ErrorException
Erroneous data format for unserializing 'Symfony\Component\Routing\CompiledRoute'

I was able to see this after enabling debugging. 

**Screenshots**

![monica-error](https://user-images.githubusercontent.com/7343812/80759976-27156680-8b06-11ea-97de-49dd3bee7374.png)

**Which version are you using:**
 - A server you maintain yourself (if so, please indicate your current version of Monica)
  Monica version 2.17.0

**Additional context**
*Environment information*
From debug page:
```
Laravel version                 6.18.2
Laravel locale                   en
Laravel config cached      true
PHP version                      7.2.30-1+ubuntu18.04.1+deb.sury.org+1
```

Log:

```
# cat laravel-2020-04-30.log
[2020-04-30 21:06:07] production.ERROR: Erroneous data format for unserializing 'Symfony\Component\Routing\CompiledRoute' {"exception":"[object] (ErrorException(code: 0): Erroneous data format for unserializing 'Symfony\\Component\\Routing\\CompiledRoute' at /var/www/monica/bootstrap/cache/routes.php:15)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Erroneous data ...', '/var/www/monica...', 15, Array)
#1 /var/www/monica/bootstrap/cache/routes.php(15): unserialize('O:34:\"Illuminat...')
#2 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(75): require('/var/www/monica...')
#3 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->Illuminate\\Foundation\\Support\\Providers\\{closure}(Object(Illuminate\\Foundation\\Application))
#4 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(844): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#5 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#6 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#7 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#8 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#9 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#10 /var/www/monica/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#11 {main}
"} 
```

**Comment by nzubair** [comment]
This happened because of  PHP version mismatch between CLI & Apache.  

`apt update` and `apt upgrade` installed php7.4 on my box. So all CLI operations were using php7.4. However, apache only had 7.2 module loaded.

To resolve this, I had to run the following:

```
sudo a2dismod php7.2
sudo a2enmod php7.4
sudo systemctl restart apache2.service
```
