### ISSUE TITLE
Heroku builds fail

### ISSUE THREAD

**Issue by tomdyson** [monicahq/monica#4640]
Clicking the Heroku button at https://github.com/monicahq/monica/blob/master/docs/installation/providers/heroku.md and following the instructions results in the following build failure:

```
-----> Installing dependencies...
       Composer version 1.10.17 2020-10-30 22:31:58
       > App\Helpers\ComposerScripts::preInstall
       PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\ComposerScripts' not found in /tmp/build_fc6f570b_/app/Helpers/ComposerScripts.php:21
       Stack trace:
       #0 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(305): App\Helpers\ComposerScripts::preInstall()
       #1 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(209): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
       #2 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch()
       #3 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/Installer.php(208): Composer\EventDispatcher\EventDispatcher->dispatchScript()
       #4 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
       #5 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/vendor/symfony/console/Command/Command.php(245): Comp in /tmp/build_fc6f570b_/app/Helpers/ComposerScripts.php on line 21
       Fatal error: Uncaught Error: Class 'Illuminate\Foundation\ComposerScripts' not found in /tmp/build_fc6f570b_/app/Helpers/ComposerScripts.php:21
       Stack trace:
       #0 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(305): App\Helpers\ComposerScripts::preInstall()
       #1 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(209): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
       #2 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch()
       #3 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/Installer.php(208): Composer\EventDispatcher\EventDispatcher->dispatchScript()
       #4 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
       #5 phar:///tmp/build_fc6f570b_/.heroku/php/bin/composer/vendor/symfony/console/Command/Command.php(245): Comp in /tmp/build_fc6f570b_/app/Helpers/ComposerScripts.php on line 21
 !     WARNING: There was a class not found error in your code
 !     ERROR: Dependency installation failed!
 !     
 !     The 'composer install' process failed with an error. The cause
 !     may be the download or installation of packages, or a pre- or
 !     post-install hook (e.g. a 'post-install-cmd' item in 'scripts')
 !     in your 'composer.json'.
```

Looking forward to trying it out!

**Comment by perivamsi** [comment]
I am facing the same issue. Appreciate any help.

**Comment by callingmedic911** [comment]
Raised an [PR](https://github.com/monicahq/monica/pull/4642). Meanwhile, you folks can [deploy from my fork](https://heroku.com/deploy?template=https://github.com/callingmedic911/monica/tree/master).

**Comment by bokane** [comment]
+1 on experiencing the issue and thank you @callingmedic911 for the PR!
