### ISSUE TITLE
Update to 3.1.0 fails with error: "Symfony\Component\Console\Helper\Helper::length()"

### ISSUE THREAD

**Issue by mgrhm** [monicahq/monica#5308]
Monica fails to update on Debian 10, which is fully up to date and running PHP 8.0.7.  When I try to update to 3.1.0 [following the instructions](https://github.com/monicahq/monica/blob/master/docs/installation/update.md), it fails and renders Monica unusable until I revert to 3.0.1.

I get this error:

    Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Console\Helper\Helper::length() in /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php:516

It looks like the problem might be with Composer, which throws the same error when I run `composer update`.  I'm running `Composer version 2.0.14 2021-05-21 17:03:37`.

I'm not sure if this is an issue specific to me, specific to Debian, some problem with Composer, or a combination of the above.

I've googled the issue and haven't found a solution.  I tried [installing php-mbstring](https://stackoverflow.com/questions/28971812/laravel-call-to-undefined-function-symfony-component-console-mb-convert-variabl#comment58320280_31079596), but it made no difference.

Here's the full output when it fails:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Helper\Helper::length() in /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php:516
Stack trace:
#0 /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php(576): Symfony\Component\Console\Helper\ProgressBar::Symfony\Component\Console\Helper\{closure}()
#1 [internal function]: Symfony\Component\Console\Helper\ProgressBar->Symfony\Component\Console\Helper\{closure}()
#2 /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php(589): preg_replace_callback()
#3 /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php(414): Symfony\Component\Console\Helper\ProgressBar->buildLine()
#4 /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php(323): Symfony\Component\Console\Helper\ProgressBar->display()
#5 phar:///usr/local/bin/composer/src/Composer/Util/Loop.php(85): Symfony\Component\Console\Helper\ProgressBar->start()
#6 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(463): Composer\Util\Loop->wait()
#7 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(340): Composer\Installer\InstallationManager->waitOnPromises()
#8 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(267): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#9 phar:///usr/local/bin/composer/src/Composer/Installer.php(707): Composer\Installer\InstallationManager->execute()
#10 phar:///usr/local/bin/composer/src/Composer/Installer.php(544): Composer\Installer->doInstall()
#11 phar:///usr/local/bin/composer/src/Composer/Installer.php(247): Composer\Installer->doUpdate()
#12 phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php(243): Composer\Installer->run()
#13 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute()
#14 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#15 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#16 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(312): Symfony\Component\Console\Application->doRun()
#17 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#18 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(124): Symfony\Component\Console\Application->run()
#19 phar:///usr/local/bin/composer/bin/composer(63): Composer\Console\Application->run()
#20 /usr/local/bin/composer(24): require('...')
#21 {main}
  thrown in /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php on line 516

Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Console\Helper\Helper::length() in /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php:516
Stack trace:
#0 /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php(576): Symfony\Component\Console\Helper\ProgressBar::Symfony\Component\Console\Helper\{closure}()
#1 [internal function]: Symfony\Component\Console\Helper\ProgressBar->Symfony\Component\Console\Helper\{closure}()
#2 /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php(589): preg_replace_callback()
#3 /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php(414): Symfony\Component\Console\Helper\ProgressBar->buildLine()
#4 /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php(323): Symfony\Component\Console\Helper\ProgressBar->display()
#5 phar:///usr/local/bin/composer/src/Composer/Util/Loop.php(85): Symfony\Component\Console\Helper\ProgressBar->start()
#6 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(463): Composer\Util\Loop->wait()
#7 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(340): Composer\Installer\InstallationManager->waitOnPromises()
#8 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(267): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#9 phar:///usr/local/bin/composer/src/Composer/Installer.php(707): Composer\Installer\InstallationManager->execute()
#10 phar:///usr/local/bin/composer/src/Composer/Installer.php(544): Composer\Installer->doInstall()
#11 phar:///usr/local/bin/composer/src/Composer/Installer.php(247): Composer\Installer->doUpdate()
#12 phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php(243): Composer\Installer->run()
#13 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute()
#14 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#15 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#16 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(312): Symfony\Component\Console\Application->doRun()
#17 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#18 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(124): Symfony\Component\Console\Application->run()
#19 phar:///usr/local/bin/composer/bin/composer(63): Composer\Console\Application->run()
#20 /usr/local/bin/composer(24): require('...')
#21 {main}
  thrown in /var/www/monica/vendor/symfony/console/Helper/ProgressBar.php on line 516
```

**Comment by asbiin** [comment]
This issue is not related to Monica itself.

Workaround: remove `vendor` directory entirely, and install composer dependencies again

```console
rm -rf vendor
composer install --no-dev
```

**Comment by mgrhm** [comment]
Thanks, @asbiin.

For anyone else having this issue, you need to pull the updated Monica *then* delete the `vendor` directory before running `composer install --no-dev`.  Doing it the other way around still results in the same error.
