### ISSUE TITLE
artisan migrate problem / 'is_birthday' in 'reminders'

### ISSUE THREAD

**Issue by ToeiRei** [monicahq/monica#535]
` PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_birthday' in 'reminders' in /home/crm/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105`

Looks like you have an error on the migrations...

Last one running correctly: 2017_08_02_124102_add_world_currencies

**Comment by djaiss** [comment]
I've made a LOT of tests before shipping 0.6.0. What can be the cause of the error?

**Comment by ToeiRei** [comment]
Not sure. I think it's 2017_08_02_152838_change_string_to_boolean_for_reminders.php

**Comment by djaiss** [comment]
Are you using mysql? I reran the migrations again from a 0.5.0 version and I don't have any issue.

**Comment by ToeiRei** [comment]
I'm using MySQL (MariaDB) and PHP 7.0.22

**Comment by ToeiRei** [comment]
All I did was running a regular update.

1. git pull
2. composer update
3. php artisan migrate

'same procedure as every year'

**Comment by djaiss** [comment]
Now the thing is to see if this is a problem for everyone or a specific use-case I didn't think about. I've made so many tests on different systems (VM, different laptops) and it worked every time.

Do you have a log we could spy on to see what's going on?

**Comment by ToeiRei** [comment]
All I got is a stack trace - nothing funky.

```
crm@webserver ~/public_html $ php artisan migrate
[2017-08-14 23:42:05] local.ERROR: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'is_birthday' in /home/crm/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /home/crm/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(449): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('ALTER TABLE rem...', Array)
#3 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('ALTER TABLE rem...', Array, Object(Closure))
#4 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection->run('ALTER TABLE rem...', Array, Object(Closure))
#5 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(86): Illuminate\Database\Connection->statement('ALTER TABLE rem...')
#6 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(239): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#7 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(148): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#8 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\Schema\Builder->table('reminders', Object(Closure))
#9 /home/crm/public_html/database/migrations/2017_08_02_152838_change_string_to_boolean_for_reminders.php(41): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#10 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): ChangeStringToBooleanForReminders->up()
#11 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(365): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#12 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(177): Illuminate\Database\Migrations\Migrator->runMigration(Object(ChangeStringToBooleanForReminders), 'up')
#13 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(146): Illuminate\Database\Migrations\Migrator->runUp('/home/crm/publi...', 5, false)
#14 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(95): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#15 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(69): Illuminate\Database\Migrations\Migrator->run(Array, Array)
#16 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#17 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#18 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#20 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#21 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#22 /home/crm/public_html/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#24 /home/crm/public_html/vendor/symfony/console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/crm/public_html/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/crm/public_html/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /home/crm/public_html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'is_birthday' in /home/crm/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107
Stack trace:
#0 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(449): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('ALTER TABLE rem...', Array)
#2 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('ALTER TABLE rem...', Array, Object(Closure))
#3 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection->run('ALTER TABLE rem...', Array, Object(Closure))
#4 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(86): Illuminate\Database\Connection->statement('ALTER TABLE rem...')
#5 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(239): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#6 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(148): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#7 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\Schema\Builder->table('reminders', Object(Closure))
#8 /home/crm/public_html/database/migrations/2017_08_02_152838_change_string_to_boolean_for_reminders.php(41): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#9 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): ChangeStringToBooleanForReminders->up()
#10 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(365): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#11 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(177): Illuminate\Database\Migrations\Migrator->runMigration(Object(ChangeStringToBooleanForReminders), 'up')
#12 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(146): Illuminate\Database\Migrations\Migrator->runUp('/home/crm/publi...', 5, false)
#13 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(95): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#14 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(69): Illuminate\Database\Migrations\Migrator->run(Array, Array)
#15 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#16 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#17 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#19 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#20 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#21 /home/crm/public_html/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#22 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 /home/crm/public_html/vendor/symfony/console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/crm/public_html/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/crm/public_html/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/crm/public_html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'is_birthday' (SQL: ALTER TABLE reminders CHANGE is_a_birthday is_birthday TINYINT(1) DEFAULT 'NULL') in /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
Stack trace:
#0 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('ALTER TABLE rem...', Array, Object(Closure))
#1 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection->run('ALTER TABLE rem...', Array, Object(Closure))
#2 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(86): Illuminate\Database\Connection->statement('ALTER TABLE rem...')
#3 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(239): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(148): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\Schema\Builder->table('reminders', Object(Closure))
#6 /home/crm/public_html/database/migrations/2017_08_02_152838_change_string_to_boolean_for_reminders.php(41): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#7 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): ChangeStringToBooleanForReminders->up()
#8 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(365): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#9 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(177): Illuminate\Database\Migrations\Migrator->runMigration(Object(ChangeStringToBooleanForReminders), 'up')
#10 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(146): Illuminate\Database\Migrations\Migrator->runUp('/home/crm/publi...', 5, false)
#11 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(95): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#12 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(69): Illuminate\Database\Migrations\Migrator->run(Array, Array)
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#17 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#18 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#19 /home/crm/public_html/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#21 /home/crm/public_html/vendor/symfony/console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/crm/public_html/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/crm/public_html/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/crm/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/crm/public_html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}



  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'is_birthday' (SQL: ALTER TABLE reminders CHANGE is_a_birthday is_birthday TINYINT(1) DEFAULT 'NULL')



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'is_birthday'



  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'is_birthday'

```

**Comment by ToeiRei** [comment]
Some additional info: `php artisan migrate:refresh` or `php artisan migrate:refresh --seed` gives complete havoc - rollbacks and migrations should work on a laravel install without problems.

Not sure what caused those issues as I did not modify the database manually. If there's anything I can do for you to track down that bugger, just let me know.

**Comment by djaiss** [comment]
This is where I'm confused. It worked flawlessly on all my tests even with fresh installs.

Let me go back to testing.

**Comment by ToeiRei** [comment]
Looks like database/migrations/2017_08_02_152838_change_string_to_boolean_for_reminders.php tried to run twice. My temp. workaround was removing that file from the migrations

**Comment by djaiss** [comment]
When you did remove it, did it worked?

**Comment by ToeiRei** [comment]
The migration went fine as far I could see

**Comment by djaiss** [comment]
So now why did it run twice? Hum.

**Comment by djaiss** [comment]
Well, that file is still important so removing it is not really an option. I'd really love to see feedback from other installations to see if it breaks as well.

**Comment by ToeiRei** [comment]
I have done the migrations manually.

**Comment by ToeiRei** [comment]
I guess it's a problem with having children added to contacts.

**Comment by djaiss** [comment]
It is not. The migration ran successfully on production (we had something like 3000 children).

**Comment by ToeiRei** [comment]
Would a database dump be useful?

**Comment by djaiss** [comment]
definitely!

**Comment by ToeiRei** [comment]
Any chance to contact you privately? Sending sensitive data on public issues sounds like a bad idea to me ;)

**Comment by djaiss** [comment]
regis AT monicahq DOT com

**Comment by djaiss** [comment]
Hopefully this issue is solved now.
