### ISSUE TITLE
Creating Gifts Fails, Contrary to UI Message

### ISSUE THREAD

**Issue by Mohammed90** [monicahq/monica#5397]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**

When trying to add a gift, the UI gives success message but nothing is reflected. No gift entries can be created at all. Including an image results in the logs provided below. The UI responds with success no matter what.

**Screenshots**

N/A

**Which version are you using:**

 - A server you maintain yourself (if so, please indicate your current version of Monica): v3.0.1

**Additional context**

I'm holding back the upgrade until the issue of search performance is resolved. Skimming the changes in the versions between v3.0.1 and latest, I don't see anything explicitly related to creating new gift entry. If the maintainers find relevance, I'll gladly upgrade.

Error log:
<details>
<pre>
 monicahq_1  | [2021-07-31 01:59:46] prodcution.ERROR: Attempt to read property "id" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php:136)
 monicahq_1  | [stacktrace]
 monicahq_1  | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php(136): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
 monicahq_1  | #1 /var/www/html/app/Http/Resources/Gift/Gift.php(24): Illuminate\\Http\\Resources\\Json\\JsonResource->__get()
 monicahq_1  | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(95): App\\Http\\Resources\\Gift\\Gift->toArray()
 monicahq_1  | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceResponse.php(39): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve()
 monicahq_1  | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(221): Illuminate\\Http\\Resources\\Json\\ResourceResponse->toResponse()
 monicahq_1  | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(774): Illuminate\\Http\\Resources\\Json\\JsonResource->toResponse()
 monicahq_1  | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(761): Illuminate\\Routing\\Router::toResponse()
 monicahq_1  | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse()
 monicahq_1  | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
 monicahq_1  | #9 /var/www/html/app/Http/Controllers/Api/ApiController.php(80): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Controllers\\Api\\ApiController->App\\Http\\Controllers\\Api\\{closure}()
 monicahq_1  | #11 /var/www/html/app/Http/Middleware/CheckLocale.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckLocale->handle()
 monicahq_1  | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
 monicahq_1  | #15 /var/www/html/app/Http/Middleware/SentryContext.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\SentryContext->handle()
 monicahq_1  | #17 /var/www/html/app/Http/Middleware/ThrottleRequestsMiddleware.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ThrottleRequestsMiddleware->handle()
 monicahq_1  | #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
 monicahq_1  | #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
 monicahq_1  | #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
 monicahq_1  | #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
 monicahq_1  | #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
 monicahq_1  | #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
 monicahq_1  | #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
 monicahq_1  | #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
 monicahq_1  | #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
 monicahq_1  | #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
 monicahq_1  | #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
 monicahq_1  | #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
 monicahq_1  | #36 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
 monicahq_1  | #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
 monicahq_1  | #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
 monicahq_1  | #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
 monicahq_1  | #41 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
 monicahq_1  | #42 {main}
 monicahq_1  | "}
</pre>
</details>

**Comment by mgrhm** [comment]
I have this same problem on 3.1.3.

The contact in question has 13 gifts already recorded.  I create the gift, Monica reports that it's been successfully created but doesn't display it.  The tab heading count of gifts does not increase -- it stays at "Gifts given (13)".

These appear to be getting added to the database, though.  I looked at a copy of the SQL file and all three attempts were successful in creating a database entry:

```
 (112,1,12,'Box of Milkies',NULL,'https://smile.amazon.co.uk/dp/B012H5THFO/',99,3,'offered','2021-08-11 00:00:00','2021-08-11 07:40:10','2021-08-11 07:40:10'),
 (113,1,12,'Box of Milkies',NULL,'https://smile.amazon.co.uk/dp/B012H5THFO/',99,3,'offered','2021-08-11 00:00:00','2021-08-11 07:41:00','2021-08-11 07:41:00'),
 (114,1,12,'Box of Milkies',NULL,0,3,'offered','2021-08-13 00:00:00','2021-08-13 12:35:41','2021-08-13 12:35:41');
```
