### ISSUE TITLE
PHP Fatal: Call to undefined method Illuminate\\Log\\LogServiceProvider::configureWeeklyHandler

### ISSUE THREAD

**Issue by turbopixel** [monicahq/monica#581]
All pages work correctly, except the start page. 

Server:

* DISTRIB_ID=Ubuntu
* DISTRIB_RELEASE=16.04
* DISTRIB_CODENAME=xenial
* DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
* PHP 7.1.8 (cli) (built: Sep  5 2017 10:10:03) ( NTS )

On the startpage /dashboard I get an HTTP Status 500 with the following error log: 

```
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #4 /var/www/<domain.tld>/vendor/...			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #3 /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\\Container\\Container->build(Object(Closure))			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #2 /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Illuminate\\Log\\LogServiceProvider->Illuminate\\Log\\{closure}(Object(Illuminate\\Foundation\\Application), Array)			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #1 /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Log/LogServiceProvider.php(18): Illuminate\\Log\\LogServiceProvider->createLogger()			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #0 /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Log/LogServiceProvider.php(36): Illuminate\\Log\\LogServiceProvider->configureHandler(Object(Illuminate\\Log\\Writer))			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: Stack trace:			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Illuminate\\Log\\LogServiceProvider::configureWeeklyHandler() in /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Log/LogServiceProvider.php:60			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #4 /var/www/<domain.tld>/vendor/...			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #3 /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\\Container\\Container->build(Object(Closure))			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #2 /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Illuminate\\Log\\LogServiceProvider->Illuminate\\Log\\{closure}(Object(Illuminate\\Foundation\\Application), Array)			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #1 /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Log/LogServiceProvider.php(18): Illuminate\\Log\\LogServiceProvider->createLogger()			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: #0 /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Log/LogServiceProvider.php(36): Illuminate\\Log\\LogServiceProvider->configureHandler(Object(Illuminate\\Log\\Writer))			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: Stack trace:			error.log
2017-09-08 12:18:19	FastCGI: server "/home/users/nico/cgi-bin/php71-fcgi" stderr: PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Illuminate\\Log\\LogServiceProvider::configureWeeklyHandler() in /var/www/<domain.tld>/vendor/laravel/framework/src/Illuminate/Log/LogServiceProvider.php:60
```

**Comment by turbopixel** [comment]
Due to a new installation the error message is now gone.
