### ISSUE TITLE
Error while upgrading while running yarn run production

### ISSUE THREAD

**Issue by niladrishekhar** [monicahq/monica#6502]
- A server you maintain yourself (if so, please indicate your current version of Monica) - Version: 3.2.0
 - PHP - PHP 8.1.13
 - nginx/1.22.1
 - mysql  Ver 15.1 Distrib 10.9.4-MariaDB

I am trying to upgrade to the latest version V3.7.0.

On running yarn run production - I am getting the following error - 
```
yarn run production
yarn run v1.22.19
$ php artisan lang:generate -vvv
Cannot load the ionCube PHP Loader - it was already loaded
Created: public/js/langs/pt-BR.json
Created: public/js/langs/zh.json
Created: public/js/langs/he.json
Created: public/js/langs/da.json
Created: public/js/langs/es.json
Created: public/js/langs/el.json
Created: public/js/langs/vendor.json
Created: public/js/langs/id.json
Created: public/js/langs/de.json
Created: public/js/langs/pt.json
Created: public/js/langs/no.json
Created: public/js/langs/uk.json
Created: public/js/langs/en.json
Created: public/js/langs/hr.json
Created: public/js/langs/tr.json
Created: public/js/langs/fi.json
Created: public/js/langs/fr.json
Created: public/js/langs/ru.json
Created: public/js/langs/sv.json
Created: public/js/langs/fa.json
Created: public/js/langs/ar.json
Created: public/js/langs/it.json
Created: public/js/langs/cs.json
Created: public/js/langs/en-GB.json
Created: public/js/langs/vi.json
Created: public/js/langs/nl.json
Created: public/js/langs/zh-TW.json
Created: public/js/langs/ja.json
$ mix --production
[webpack-cli] Error: Cannot find module 'vue/compiler-sfc'
Require stack:
- /var/www/monica/node_modules/vue-loader/dist/index.js
- /var/www/monica/node_modules/laravel-mix/src/components/Vue.js
- /var/www/monica/node_modules/laravel-mix/src/components/ComponentRegistrar.js
- /var/www/monica/node_modules/laravel-mix/src/Mix.js
- /var/www/monica/node_modules/laravel-mix/setup/webpack.config.js
- /var/www/monica/node_modules/webpack-cli/lib/webpack-cli.js
- /var/www/monica/node_modules/webpack-cli/lib/bootstrap.js
- /var/www/monica/node_modules/webpack-cli/bin/cli.js
- /var/www/monica/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/var/www/monica/node_modules/vue-loader/dist/index.js:8:24)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/monica/node_modules/vue-loader/dist/index.js',
    '/var/www/monica/node_modules/laravel-mix/src/components/Vue.js',
    '/var/www/monica/node_modules/laravel-mix/src/components/ComponentRegistrar.js',
    '/var/www/monica/node_modules/laravel-mix/src/Mix.js',
    '/var/www/monica/node_modules/laravel-mix/setup/webpack.config.js',
    '/var/www/monica/node_modules/webpack-cli/lib/webpack-cli.js',
    '/var/www/monica/node_modules/webpack-cli/lib/bootstrap.js',
    '/var/www/monica/node_modules/webpack-cli/bin/cli.js',
    '/var/www/monica/node_modules/webpack/bin/webpack.js'
  ]
}


npm install vue/compiler-sfc
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/vue/compiler-sfc.git
npm ERR! Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-31T14_54_13_564Z-debug-0.log

```
Can anyone please help.

**Comment by niladrishekhar** [comment]
I tried a little more searching and did some experiment with the vue.js and now when I run the yarn install production I get this series of errors - 

`ERROR in ./resources/js/components/dashboard/DashboardLog.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/journal/JournalList.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/journal/RateDay.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/journal/partials/JournalCalendar.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/journal/partials/JournalContentActivity.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/journal/partials/JournalContentEntry.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/journal/partials/JournalContentRate.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/Avatar.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/Confirm.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/SpecialDate.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/SpecialDeceased.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/form/Checkbox.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/form/Date.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/form/Input.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/form/Radio.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/form/Select.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/form/Textarea.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/partials/form/Toggle.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/passport/AuthorizedClients.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/passport/Clients.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/passport/PersonalAccessTokens.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/Addresses.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/Archive.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/ContactInformation.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/ContactList.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/ContactMultiSearch.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/ContactSearch.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/ContactSelect.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/MeContact.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/Notes.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/Pets.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/SetAvatar.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/SetFavorite.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/StayInTouch.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/Tags.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/Tasks.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/activity/ActivityList.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/calls/LastCalled.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/calls/PhoneCallList.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/conversation/Conversation.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/conversation/ConversationList.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/conversation/Message.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/document/DocumentList.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/gifts/Gifts.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/lifeevent/CreateLifeEvent.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/lifeevent/LifeEventList.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/lifeevent/content/CreateDefaultLifeEvent.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/people/photo/PhotoList.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/ActivityTypes.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/ContactFieldTypes.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/DAVResources.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/Genders.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/LifeEventTypes.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/MfaActivate.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/Modules.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/RecoveryCodes.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/ReminderRules.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/ReminderTime.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/Subscription.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

ERROR in ./resources/js/components/settings/WebauthnConnector.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/var/www/monica/node_modules/vue-loader/dist/index.js:71:34)

webpack compiled with 60 errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
