### ISSUE TITLE
production.ERROR: This database engine does not support fulltext search operations

### ISSUE THREAD

**Issue by cellulosa** [monicahq/monica#6943]
## Bug description

When performing a search on monica-next I get:

```shell
[2023-10-18 14:13:32] production.ERROR: This database engine does not support fulltext search operations. {"userId":"user-id","exception":"[object] (RuntimeException(code: 0): This database engine does not support fulltext search operations. at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php:706)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(222): Illuminate\\Database\\Query\\Grammars\\Grammar->whereFullText(Object(Illuminate\\Database\\Query\\Builder), Array)
#1 [internal function]: Illuminate\\Database\\Query\\Grammars\\Grammar->Illuminate\\Database\\Query\\Grammars\\{closure}(Array, 2)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map(Object(Closure), Array, Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\\Support\\Arr::map(Array, Object(Closure))
172.20.0.1 - - [18/Oct/2023:14:13:32 +0000] "POST /vaults/vault-id/search HTTP/1.1" 500 1575 "http://localhost:8080/vaults/vault-id/search" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0"
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(221): Illuminate\\Support\\Collection->map(Object(Closure))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(206): Illuminate\\Database\\Query\\Grammars\\Grammar->compileWheresToArray(Object(Illuminate\\Database\\Query\\Builder))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(509): Illuminate\\Database\\Query\\Grammars\\Grammar->compileWheres(Object(Illuminate\\Database\\Query\\Builder))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(222): Illuminate\\Database\\Query\\Grammars\\Grammar->whereNested(Object(Illuminate\\Database\\Query\\Builder), Array)
#8 [internal function]: Illuminate\\Database\\Query\\Grammars\\Grammar->Illuminate\\Database\\Query\\Grammars\\{closure}(Array, 0)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map(Object(Closure), Array, Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(221): Illuminate\\Support\\Collection->map(Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(206): Illuminate\\Database\\Query\\Grammars\\Grammar->compileWheresToArray(Object(Illuminate\\Database\\Query\\Builder))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(101): Illuminate\\Database\\Query\\Grammars\\Grammar->compileWheres(Object(Illuminate\\Database\\Query\\Builder), Array)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(75): Illuminate\\Database\\Query\\Grammars\\Grammar->compileComponents(Object(Illuminate\\Database\\Query\\Builder))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2638): Illuminate\\Database\\Query\\Grammars\\Grammar->compileSelect(Object(Illuminate\\Database\\Query\\Builder))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2752): Illuminate\\Database\\Query\\Builder->toSql()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2740): Illuminate\\Database\\Query\\Builder->runSelect()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3294): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2739): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(737): Illuminate\\Database\\Query\\Builder->get(Array)
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(721): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#22 /var/www/html/vendor/laravel/scout/src/Engines/DatabaseEngine.php(157): Illuminate\\Database\\Eloquent\\Builder->get()
#23 /var/www/html/vendor/laravel/scout/src/Engines/DatabaseEngine.php(56): Laravel\\Scout\\Engines\\DatabaseEngine->searchModels(Object(Laravel\\Scout\\Builder))
#24 /var/www/html/vendor/laravel/scout/src/Engines/Engine.php(136): Laravel\\Scout\\Engines\\DatabaseEngine->search(Object(Laravel\\Scout\\Builder))
#25 /var/www/html/vendor/laravel/scout/src/Builder.php(337): Laravel\\Scout\\Engines\\Engine->get(Object(Laravel\\Scout\\Builder))
#26 /var/www/html/app/Domains/Vault/Search/Web/ViewHelpers/VaultSearchIndexViewHelper.php(34): Laravel\\Scout\\Builder->get()
#27 /var/www/html/app/Domains/Vault/Search/Web/ViewHelpers/VaultSearchIndexViewHelper.php(18): App\\Domains\\Vault\\Search\\Web\\ViewHelpers\\VaultSearchIndexViewHelper::contacts(Object(App\\Models\\Vault), 'pizzaa')
#28 /var/www/html/app/Domains/Vault/Search/Web/Controllers/VaultSearchController.php(29): App\\Domains\\Vault\\Search\\Web\\ViewHelpers\\VaultSearchIndexViewHelper::data(Object(App\\Models\\Vault), 'pizzaa')
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Domains\\Vault\\Search\\Web\\Controllers\\VaultSearchController->show(Object(Illuminate\\Http\\Request), '9a585588-5c92-4...')
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('show', Array)
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Domains\\Vault\\Search\\Web\\Controllers\\VaultSearchController), 'show')
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\EnsureEmailIsVerified->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/html/vendor/inertiajs/inertia-laravel/src/Middleware.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Inertia\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/html/vendor/laravel/jetstream/src/Http/Middleware/ShareInertiaData.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Jetstream\\Http\\Middleware\\ShareInertiaData->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'vault-viewer', 'vault')
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'sanctum')
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/www/html/vendor/codezero/laravel-localizer/src/Middleware/SetLocale.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): CodeZero\\Localizer\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(89): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#85 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#86 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#87 {main}
"} 
```

## How to reproduce

1. Create `docker-composer.yml` with the following and launch with `docker-compose up`:

```yaml
  monica:
    container_name: monica
    image: ghcr.io/monicahq/monica-next:main
    volumes:
      - ${DOCKER_CONFIG_DIR}/monica/database.sqlite:/var/www/html/storage/database.sqlite
    environment:
      - APP_ENV=production
      - APP_URL=https://my-website.com
      - APP_TRUSTED_PROXIES=*
      - APP_KEY=${MONICA_APP_KEY}
      - DB_DATABASE=/var/www/html/storage/database.sqlite
      - DB_PASSWORD=${MONICA_MYSQL_PASS}
      - MAIL_MAILER=log
      - MEILISEARCH_HOST=monica-meilisearch
      - MEILISEARCH_KEY=${MONICA_MEILI_MASTER_KEY}
    ports:
      - 8080:80
    restart: unless-stopped

  monica-meilisearch:
    container_name: monica-meilisearch
    image: getmeili/meilisearch:latest
    depends_on:
      - monica
    volumes:
      - ${DOCKER_CONFIG_DIR}/monica/meilisearch:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MONICA_MEILI_MASTER_KEY}
    restart: unless-stopped
```

2. Configure and run a queue with `docker exec monica php artisan queue:listen --queue=high,low,default` ([as per tutorial](https://docs.monicahq.com/developers/setup-local-development))

## Environment

- self-hosted instance

**Comment by Karunamon** [comment]
Another +1 here, worth noting that this breaks the ability to add relationships between contacts, since the contact selector is a search box.

**Comment by asbiin** [comment]
SQLite doesn't support fulltext, so you can't activate meiliseach (scout) with SQLite.
Anyway, for production ready instance, you should switch to mysql/mariadb/postgres.

**Comment by Karunamon** [comment]
This is not related specifically to meilisearch , again, this exact error message presents itself when trying to add a contact relationship.

**Comment by virtadpt** [comment]
> SQLite doesn't support fulltext, so you can't activate meiliseach (scout) with SQLite. Anyway, for production ready instance, you should switch to mysql/mariadb/postgres.

It does support fulltext search, but it requires a schema change and some different queries: https://www.sqlite.org/fts5.html

**Comment by asbiin** [comment]
> > SQLite doesn't support fulltext, so you can't activate meiliseach (scout) with SQLite. Anyway, for production ready instance, you should switch to mysql/mariadb/postgres.
> 
> It does support fulltext search, but it requires a schema change and some different queries: https://www.sqlite.org/fts5.html

Don't hesitate to open a pull request to fix it! Any help would be appreciated.
