### ISSUE TITLE
[Bug: Chandler] Deleting a contact results in a null exception error on reminders

### ISSUE THREAD

**Issue by lenaxia** [monicahq/monica#7484]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

When deleting a contact it results in a server 5xx error

### Steps to reproduce

1. Create a contact
2. Create a reminder attached to the contact
3. Delete the contact
4. ???
5. Error

### Expected behavior

No Error.

Here is the suggested fix from my LLM:
======================================================

It looks like the issue is arising because the contact associated with a reminder no longer exists in the database after you deleted it. This causes the `$contact` object to be null, leading to the error when trying to access its properties.

To handle this gracefully, you can add a null check for the `$contact` object in your `upcomingReminders` method. Here’s the updated code with the null check:

`app/Domains/Vault/ManageVault/Web/ViewHelpers/VaultShowViewHelper.php`
```php
public static function upcomingReminders(Vault $vault, User $user): array
{
    $currentDate = Carbon::now()->copy();
    $currentDate->second = 0;

    // first we get all the user notification channels for the users in the vault
    $userNotificationChannels = $vault->users->flatMap(fn ($u) => $u->notificationChannels);

    // then we get all the contact reminders scheduled for those channels
    $contactRemindersScheduled = $userNotificationChannels->flatMap(
        fn ($channel) => $channel->contactReminders()
            ->wherePivot('scheduled_at', '<=', $currentDate->addDays(30))
            ->wherePivot('triggered_at', null)
            ->orderByPivot('scheduled_at', 'asc')
            ->get()
    );

    // finally, we get all the details about those reminders
    $remindersCollection = $contactRemindersScheduled->map(function ($reminder) use ($vault, $user) {
        $contact = $reminder->contact;

        if (!$contact || $contact->vault_id !== $vault->id) {
            return null;
        }

        $scheduledAtDate = Carbon::createFromFormat('Y-m-d H:i:s', $reminder->pivot->scheduled_at);

        return [
            'id' => $reminder->id,
            'label' => $reminder->label,
            'scheduled_at' => DateHelper::format($scheduledAtDate, $user),
            'contact' => [
                'id' => $contact->id,
                'name' => $contact->name,
                'avatar' => $contact->avatar,
                'url' => [
                    'show' => route('contact.show', [
                        'vault' => $contact->vault_id,
                        'contact' => $contact->id,
                    ]),
                ],
            ],
        ];
    });

    // this line removes the null values that are added when the contact
    // is not in the vault (or doesn't exist)
    $remindersCollection = $remindersCollection->filter(fn ($value) => $value != null);

    return [
        'reminders' => $remindersCollection,
        'url' => [
            'index' => route('vault.reminder.index', [
                'vault' => $vault->id,
            ]),
        ],
    ];
}
```

### Explanation:
- **Null Check**: Added a check `if (!$contact || $contact->vault_id !== $vault->id)` to ensure that the contact exists and belongs to the correct vault before accessing its properties.
- **Filtering**: The existing filter at the end will remove any null entries, ensuring that only valid reminders are returned.

This should prevent the error from occurring when a contact is deleted. If you still encounter issues, make sure to clear the cache and config:

```sh
php artisan cache:clear
php artisan config:clear
```

Let me know if this resolves the issue! 🐬

### Environment

Your own self-hosted instance (v5 a.k.a chandler version or main branch)

### Version of Monica

Version 5.0.0-beta.4 — commit 0400350.

### Installation method

Docker image

### Web server

Other

### Database engine version

PostgreSQL

### Additional info

Running this in Kubernetes with the monica-next:main image. 

Logs:
```
APP_KEY already set.
Database ready.
✓ Clear config cache

   INFO  Configuration cache cleared successfully.

✓ Resetting route cache

   INFO  Routes cached successfully.

✓ Resetting view cache

   INFO  Compiled views cleared successfully.

✓ Resetting event cache

   INFO  Events cached successfully.

✓ Symlink the storage folder

   INFO  The [public/storage] link has been connected to [storage/app/public].

✓ Performing migrations

   INFO  Preparing database.

  Creating migration table ...................................... 38.25ms DONE

   INFO  Running migrations.

  2013_04_25_132851_create_accounts_table ....................... 51.83ms DONE
  2013_04_25_155842_create_attributes_table .................... 143.46ms DONE
  2014_10_12_000000_create_users_table .......................... 45.04ms DONE
  2014_10_12_000010_create_vaults_table ......................... 35.49ms DONE
  2014_10_12_100000_create_password_resets_table ................ 26.43ms DONE
  2014_10_12_200000_add_two_factor_columns_to_users_table ....... 30.32ms DONE
  2018_08_08_100000_create_telescope_entries_table ............. 195.07ms DONE
  2018_12_29_135516_create_synctokens ........................... 54.08ms DONE
  2019_03_29_163611_create_webauthn_keys ........................ 53.17ms DONE
  2019_05_05_194746_create_crons ................................ 50.52ms DONE
  2019_08_19_000000_create_failed_jobs_table .................... 53.57ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ......... 58.31ms DONE
  2020_02_17_224235_create_genders_table ........................ 27.97ms DONE
  2020_02_19_173445_create_pronouns_table ....................... 29.22ms DONE
  2020_03_20_213318_create_address_types_table .................. 30.60ms DONE
  2020_04_23_133132_create_companies_table ...................... 25.81ms DONE
  2020_04_25_133132_create_contacts_table ...................... 220.16ms DONE
  2020_04_26_215133_create_addresses_table ...................... 51.50ms DONE
  2021_07_06_065356_create_user_token_socialite ................. 39.99ms DONE
  2021_10_09_204235_create_group_table ......................... 178.14ms DONE
  2021_10_16_184625_create_relationship_types_table ............ 213.29ms DONE
  2021_10_18_000002_create_pets_table ........................... 74.22ms DONE
  2021_10_19_022411_create_contact_feed_table ................... 33.90ms DONE
  2021_10_19_192432_create_labels_table ......................... 59.15ms DONE
  2021_10_20_004100_create_contact_fields_table ................. 75.18ms DONE
  2021_10_20_163535_create_emotions_table ....................... 33.45ms DONE
  2021_10_21_013005_create_notes_table .......................... 78.01ms DONE
  2022_01_22_183321_create_jobs_table ........................... 39.97ms DONE
  2022_02_09_145139_create_contact_date_table ................... 70.01ms DONE
  2022_02_18_215852_create_reminders_table ..................... 151.49ms DONE
  2022_02_24_002342_create_files_table .......................... 67.35ms DONE
  2022_03_22_180407_create_currencies_table ..................... 60.97ms DONE
  2022_03_23_005751_create_loans_table .......................... 71.08ms DONE
  2022_05_13_201216_create_contact_tasks_table .................. 43.17ms DONE
  2022_05_16_184121_create_call_reasons_table ................... 68.03ms DONE
  2022_05_16_193917_create_calls_table .......................... 62.66ms DONE
  2022_05_17_155546_create_life_events_table ................... 223.82ms DONE
  2022_06_02_011219_create_goals_table .......................... 67.61ms DONE
  2022_06_09_173049_create_gifts_table ......................... 172.65ms DONE
  2022_07_31_200647_create_sessions_table ....................... 55.89ms DONE
  2022_07_31_200800_create_cache_table .......................... 68.81ms DONE
  2022_09_20_183401_create_journal_table ........................ 45.67ms DONE
  2022_09_22_111510_create_posts_table ......................... 247.82ms DONE
  2022_10_30_202904_create_religions_table ...................... 48.04ms DONE
  2022_11_01_174411_add_religion_to_contact ..................... 23.25ms DONE
  2022_11_16_221702_create_job_batches_table .................... 38.29ms DONE
  2022_12_15_004442_create_slices_of_life_table ................. 64.12ms DONE
  2023_01_07_005110_create_mood_tracking_parameters_table ....... 34.68ms DONE
  2023_01_08_155554_create_mood_tracking_table .................. 48.11ms DONE
  2023_02_07_022607_create_vault_quick_facts_template_table ..... 73.81ms DONE
  2023_03_16_182310_create_post_metrics_table ................... 62.03ms DONE
  2023_03_31_125903_create_life_metrics_table ................... 58.73ms DONE
  2023_05_06_125432_add_contact_sort_order_to_users ............. 11.02ms DONE
  2023_06_12_093907_add_instance_administrator .................. 12.50ms DONE
  2023_06_16_103430_fix_call_reasons ............................. 9.84ms DONE
  2023_06_28_102228_fix_locale ................................... 4.81ms DONE
  2023_07_02_230200_fix_synctokens ............................... 9.10ms DONE
  2023_07_03_230200_create_addressbook_subscription ............. 67.29ms DONE
  2023_07_29_200200_add_contact_distant_uri ..................... 12.82ms DONE
  2023_07_29_200200_add_groups_distant_uri ...................... 19.11ms DONE
  2023_08_22_175035_fix_group_grouptype ......................... 20.30ms DONE
  2023_08_30_202650_create_logs_table ........................... 70.15ms DONE
  2023_08_30_202650_fix_addressbook_currentlogid ................. 6.71ms DONE
  2023_10_02_195229_add_can_be_deleted_to_templates ............. 10.02ms DONE
  2023_10_06_064814_rename_locales .............................. 15.70ms DONE
  2024_05_12_170430_add_fails_to_notification_channels .......... 19.20ms DONE

✓ Generate api documentation
ⓘ Processing route: [GET] api/user
✔ Processed route: [GET] api/user
ⓘ Processing route: [GET] api/users
✔ Processed route: [GET] api/users
ⓘ Processing route: [GET] api/users/{user}
✔ Processed route: [GET] api/users/{user}
ⓘ Processing route: [GET] api/vaults
✔ Processed route: [GET] api/vaults
ⓘ Processing route: [POST] api/vaults
✔ Processed route: [POST] api/vaults
ⓘ Processing route: [GET] api/vaults/{vault}
✔ Processed route: [GET] api/vaults/{vault}
ⓘ Processing route: [PUT,PATCH] api/vaults/{vault}
✔ Processed route: [PUT,PATCH] api/vaults/{vault}
ⓘ Processing route: [DELETE] api/vaults/{vault}
✔ Processed route: [DELETE] api/vaults/{vault}
ⓘ Extracting intro and auth Markdown files to: .scribe
✔ Extracted intro and auth Markdown files to: .scribe
ⓘ Writing Blade docs...
✔ Wrote Blade docs to: resources/views/scribe/
✔ Wrote Laravel assets to: public/vendor/scribe/
ⓘ Generating Postman collection
✔ Wrote Postman collection to: storage/app/scribe/collection.json
ⓘ Generating OpenAPI specification
✔ Wrote OpenAPI specification to: storage/app/scribe/openapi.yaml
Checking for any pending upgrades to your config file...

✔ All done. Visit your docs at https://monica.domain.tld/docs
✓ Cache configuraton

   INFO  Configuration cached successfully.

✓ Setup scout
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.3.36. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.3.36. Set the 'ServerName' directive globally to suppress this message
[Thu Dec 05 19:33:45.996467 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.3.13 configured -- resuming normal operations
[Thu Dec 05 19:33:45.996500 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

71.197.219.98 - - [05/Dec/2024:20:20:37 +0000] "GET /vaults HTTP/1.1" 200 27973 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
[2024-12-05 20:20:38] production.ERROR: Attempt to read property "vault_id" on null {"userId":"9da77fd1-863d-4f85-a23e-244e9f12cfd9","exception":"[object] (ErrorException(code: 0): Attempt to read property \"vault_id\" on null at /var/www/html/app/Domains/Vault/ManageVault/Web/ViewHelpers/VaultShowViewHelper.php:58)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Attempt to read...', '/var/www/html/a...', 58)
#1 /var/www/html/app/Domains/Vault/ManageVault/Web/ViewHelpers/VaultShowViewHelper.php(58): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Attempt to read...', '/var/www/html/a...', 58)
#2 [internal function]: App\\Domains\\Vault\\ManageVault\\Web\\ViewHelpers\\VaultShowViewHelper::App\\Domains\\Vault\\ManageVault\\Web\\ViewHelpers\\{closure}(Object(App\\Models\\ContactReminder), 0)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map(Object(Closure), Array, Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(791): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#5 /var/www/html/app/Domains/Vault/ManageVault/Web/ViewHelpers/VaultShowViewHelper.php(55): Illuminate\\Support\\Collection->map(Object(Closure))
#6 /var/www/html/app/Domains/Vault/ManageVault/Web/Controllers/VaultController.php(71): App\\Domains\\Vault\\ManageVault\\Web\\ViewHelpers\\VaultShowViewHelper::upcomingReminders(Object(App\\Models\\Vault), Object(App\\Models\\User))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Domains\\Vault\\ManageVault\\Web\\Controllers\\VaultController->show(Object(Illuminate\\Http\\Request), Object(App\\Models\\Vault))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('show', Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Domains\\Vault\\ManageVault\\Web\\Controllers\\VaultController), 'show')
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(210): Illuminate\\Routing\\Route->runController()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\EnsureEmailIsVerified->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/AddLinkHeadersForPreloadedAssets.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\AddLinkHeadersForPreloadedAssets->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /var/www/html/vendor/inertiajs/inertia-laravel/src/Middleware.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Inertia\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/html/vendor/laravel/jetstream/src/Http/Middleware/ShareInertiaData.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\\Jetstream\\Http\\Middleware\\ShareInertiaData->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'view', 'vault')
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(64): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'sanctum')
#29 /var/www/html/vendor/codezero/laravel-localizer/src/Middleware/SetLocale.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): CodeZero\\Localizer\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1188): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#69 /var/www/html/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#70 {main}
"}
71.197.219.98 - - [05/Dec/2024:20:20:38 +0000] "GET /vaults/9da7800e-20f4-440d-91dc-9277b1ae4a5b HTTP/1.1" 500 8185 "https://monica.thekao.cloud/vaults" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
```

**Comment by DUC-ANH-LY** [comment]
@lenaxia Seem it fixed , can you closed the issue
