### ISSUE TITLE
"npm run prod" error

### ISSUE THREAD

**Issue by yoginth** [monicahq/monica#750]
Node Version : 8.9.4
NPM Version : 5.5.1

I Tried to compile is SCSS files using `npm run prod, dev, watch` it returned error

```
> @ prod /var/www/html
> npm run production


> @ production /var/www/html
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                           

 ERROR  Failed to compile with 2 errors                                                                                       14:08:31

 error  in ./resources/assets/sass/app.scss

Module build failed: 
@import "~jquery-tags-input/dist/jquery.tagsinput.min";
^
      File to import not found or unreadable: ~jquery-tags-input/dist/jquery.tagsinput.min.
Parent style sheet: stdin
      in /var/www/html/resources/assets/sass/app.scss (line 7, column 1)

 @ ./resources/assets/sass/app.scss 4:14-266
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

 error  in ./resources/assets/sass/app.scss

Module build failed: ModuleBuildError: Module build failed: 
@import "~jquery-tags-input/dist/jquery.tagsinput.min";
^
      File to import not found or unreadable: ~jquery-tags-input/dist/jquery.tagsinput.min.
Parent style sheet: stdin
      in /var/www/html/resources/assets/sass/app.scss (line 7, column 1)
    at runLoaders (/var/www/html/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/var/www/html/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/var/www/html/node_modules/async/dist/async.js:2244:31)
    at Object.callback (/var/www/html/node_modules/async/dist/async.js:906:16)
    at options.error (/var/www/html/node_modules/node-sass/lib/index.js:294:32)

         Asset    Size  Chunks                    Chunk Names
    /js/app.js  492 kB       0  [emitted]  [big]  /js/app
/js/app.js.map  509 kB       0  [emitted]         /js/app

ERROR in ./node_modules/css-loader?{"url":true,"sourceMap":true,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/var/www/html/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
Module build failed: 
@import "~jquery-tags-input/dist/jquery.tagsinput.min";
^
      File to import not found or unreadable: ~jquery-tags-input/dist/jquery.tagsinput.min.
Parent style sheet: stdin
      in /var/www/html/resources/assets/sass/app.scss (line 7, column 1)
 @ ./resources/assets/sass/app.scss 4:14-266
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleBuildError: Module build failed: 
@import "~jquery-tags-input/dist/jquery.tagsinput.min";
^
      File to import not found or unreadable: ~jquery-tags-input/dist/jquery.tagsinput.min.
Parent style sheet: stdin
      in /var/www/html/resources/assets/sass/app.scss (line 7, column 1)
    at runLoaders (/var/www/html/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/var/www/html/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/var/www/html/node_modules/async/dist/async.js:2244:31)
    at Object.callback (/var/www/html/node_modules/async/dist/async.js:906:16)
    at options.error (/var/www/html/node_modules/node-sass/lib/index.js:294:32)
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yoginth/.npm/_logs/2018-01-05T06_08_32_142Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yoginth/.npm/_logs/2018-01-05T06_08_32_179Z-debug.log
```

**Comment by djaiss** [comment]
Silly question, but have you tried deleting `node_modules` folder and `npm install` again?

**Comment by shibinv** [comment]
I had to change 
```
@import "~jquery-tags-input/dist/jquery.tagsinput.min";
```
to
```
@import "~jQuery-Tags-Input/dist/jquery.tagsinput.min";
```
in `resources/assets/sass/app.scss`
