### ISSUE TITLE
Dashboard in production is not working 

### ISSUE THREAD

**Issue by anitawoodruff** [monicahq/monica#768]
It just says 'Whoops, something went wrong' for me. Is it down?

**Comment by djaiss** [comment]
@anitawoodruff no. I'm going to investigate why it's not working. I've completely changed the dashboard, perhaps there is a use case I didn't take into account. I'll try to fix that in the next hours. Sorry about that!

**Comment by djaiss** [comment]
There are errors indeed. Here is the log

```php
ErrorException: count(): Parameter must be an array or an object that implements Countable
#62 app/Contact.php(1376): handleError
#61 vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): handleError
#60 vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(0): count
#59 app/Contact.php(1376): getRelatedRealContact
#58 storage/framework/views/edaa347ed3804817c515a787f5bbc7ae57f65eac.php(11): include
#57 vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): evaluatePath
#56 vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): get
#55 vendor/laravel/framework/src/Illuminate/View/View.php(137): getContents
#54 vendor/laravel/framework/src/Illuminate/View/View.php(120): renderContents
#53 vendor/laravel/framework/src/Illuminate/View/View.php(85): render
#52 storage/framework/views/9b8954f257ceed5cdc8712cd902229c89b7df3a2.php(41): include
#51 vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): evaluatePath
#50 vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): get
#49 vendor/laravel/framework/src/Illuminate/View/View.php(137): getContents
#48 vendor/laravel/framework/src/Illuminate/View/View.php(120): renderContents
#47 vendor/laravel/framework/src/Illuminate/View/View.php(85): render
#46 vendor/laravel/framework/src/Illuminate/Http/Response.php(42): setContent
#45 vendor/symfony/http-foundation/Response.php(200): __construct
#44 vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): toResponse
#43 vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): prepareResponse
#42 vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\{closure}
#41 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#40 app/Http/Middleware/CheckVersion.php(32): handle
#39 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#38 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#37 app/Http/Middleware/CheckLocale.php(25): handle
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#35 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#34 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): handle
#33 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#32 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#31 vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): handle
#30 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#29 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#28 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): handle
#27 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#26 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#25 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): handle
#24 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#23 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#22 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): handle
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#20 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#19 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): handle
#18 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#17 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#16 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): handle
#15 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#14 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#13 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#12 vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): runRouteWithinStack
#11 vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): runRoute
#10 vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): dispatchToRoute
#9 vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): dispatch
#8 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\{closure}
#7 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#6 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): handle
#5 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#4 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#3 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): sendRequestThroughRouter
#1 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): handle
#0 public/index.php(52): null
ErrorException: count(): Parameter must be an array or an object that implements Countable (View: /home/forge/default/resources/views/dashboard/_monthReminder.blade.php)
#58 app/Contact.php(1376): handleViewException
#57 vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): evaluatePath
#56 vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): get
#55 vendor/laravel/framework/src/Illuminate/View/View.php(137): getContents
#54 vendor/laravel/framework/src/Illuminate/View/View.php(120): renderContents
#53 vendor/laravel/framework/src/Illuminate/View/View.php(85): render
#52 storage/framework/views/9b8954f257ceed5cdc8712cd902229c89b7df3a2.php(41): include
#51 vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): evaluatePath
#50 vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): get
#49 vendor/laravel/framework/src/Illuminate/View/View.php(137): getContents
#48 vendor/laravel/framework/src/Illuminate/View/View.php(120): renderContents
#47 vendor/laravel/framework/src/Illuminate/View/View.php(85): render
#46 vendor/laravel/framework/src/Illuminate/Http/Response.php(42): setContent
#45 vendor/symfony/http-foundation/Response.php(200): __construct
#44 vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): toResponse
#43 vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): prepareResponse
#42 vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\{closure}
#41 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#40 app/Http/Middleware/CheckVersion.php(32): handle
#39 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#38 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#37 app/Http/Middleware/CheckLocale.php(25): handle
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#35 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#34 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): handle
#33 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#32 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#31 vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): handle
#30 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#29 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#28 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): handle
#27 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#26 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#25 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): handle
#24 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#23 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#22 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): handle
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#20 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#19 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): handle
#18 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#17 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#16 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): handle
#15 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#14 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#13 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#12 vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): runRouteWithinStack
#11 vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): runRoute
#10 vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): dispatchToRoute
#9 vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): dispatch
#8 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\{closure}
#7 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#6 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): handle
#5 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#4 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#3 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): sendRequestThroughRouter
#1 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): handle
#0 public/index.php(52): null
ErrorException: count(): Parameter must be an array or an object that implements Countable (View: /home/forge/default/resources/views/dashboard/_monthReminder.blade.php) (View: /home/forge/default/resources/views/dashboard/_monthReminder.blade.php)
#52 app/Contact.php(1376): handleViewException
#51 vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): evaluatePath
#50 vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): get
#49 vendor/laravel/framework/src/Illuminate/View/View.php(137): getContents
#48 vendor/laravel/framework/src/Illuminate/View/View.php(120): renderContents
#47 vendor/laravel/framework/src/Illuminate/View/View.php(85): render
#46 vendor/laravel/framework/src/Illuminate/Http/Response.php(42): setContent
#45 vendor/symfony/http-foundation/Response.php(200): __construct
#44 vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): toResponse
#43 vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): prepareResponse
#42 vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\{closure}
#41 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#40 app/Http/Middleware/CheckVersion.php(32): handle
#39 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#38 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#37 app/Http/Middleware/CheckLocale.php(25): handle
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#35 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#34 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): handle
#33 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#32 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#31 vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): handle
#30 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#29 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#28 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): handle
#27 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#26 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#25 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): handle
#24 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#23 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#22 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): handle
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#20 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#19 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): handle
#18 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#17 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#16 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): handle
#15 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#14 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#13 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#12 vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): runRouteWithinStack
#11 vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): runRoute
#10 vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): dispatchToRoute
#9 vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): dispatch
#8 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\{closure}
#7 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#6 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): handle
#5 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#4 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#3 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): sendRequestThroughRouter
#1 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): handle
#0 public/index.php(52): null
```

**Comment by djaiss** [comment]
Thanks @anitawoodruff for the bug report. Really appreciate it. I've found the error and will push the fix in a few minutes.

**Comment by djaiss** [comment]
@anitawoodruff it should be fixed in production. Can you verify? Thanks again!

**Comment by anitawoodruff** [comment]
Yep, working now at https://app.monicahq.com/dashboard . Thanks! :D
