### ISSUE TITLE
Error: Crash due to validation when adding a new call log

### ISSUE THREAD

**Issue by erdmenchen** [monicahq/monica#820]
When adding a call log, and deleting/clearing the timestamp and submitting the call log, Monica crashes with the following error in the log:
```
production.ERROR: Data missing {"userId":1,"email":"[...]","exception":"[object] (InvalidArgumentException(code: 0): Data missing at [...]/vendor/nesbot/carbon/src/Carbon/Carbon.php:582)
[stacktrace]
#0 [...]/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(715): Carbon\\Carbon::createFromFormat('Y-m-d H:i:s', '')
#1 [...]/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(355): Illuminate\\Database\\Eloquent\\Model->asDateTime('')
#2 [...]/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(313): Illuminate\\Database\\Eloquent\\Model->getAttributeValue('called_at')
#3 [...]/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1360): Illuminate\\Database\\Eloquent\\Model->getAttribute('called_at')
#4 [...]/app/Contact.php(889): Illuminate\\Database\\Eloquent\\Model->__get('called_at')
#5 [...]/app/Http/Controllers/Contacts/CallsController.php(33): App\\Contact->updateLastCalledInfo(Object(App\\Call))
#6 [internal function]: App\\Http\\Controllers\\Contacts\\CallsController->store(Object(App\\Http\\Requests\\People\\CallsRequest), Object(App\\Contact))
```
Also it looks like the modal is not reset when aborting/cancelling. 

The root cause seems to me like there is no validation at all in https://github.com/monicahq/monica/blob/master/app/Http/Controllers/Contacts/CallsController.php
And no validation handling in the view as well...

Also it looks like the modal is not reset when aborting/cancelling.

**Comment by pqhf5kd** [comment]
This is no longer an issue on hosted Monica Version: 2.11.2

**Comment by djaiss** [comment]
Closing, we'll reopen if that's still the case.
